default: cpsc2150/banking/controllers/IMortgageController.java cpsc2150/banking/controllers/MortgageController.java cpsc2150/banking/models/AbsCustomer.java cpsc2150/banking/models/AbsMortgage.java cpsc2150/banking/models/Customer.java cpsc2150/banking/models/ICustomer.java cpsc2150/banking/models/IMortgage.java cpsc2150/banking/models/Mortgage.java cpsc2150/banking/views/IMortgageView.java cpsc2150/banking/views/MortgageView.java cpsc2150/banking/MortgageApp.java
	javac cpsc2150/banking/controllers/IMortgageController.java cpsc2150/banking/controllers/MortgageController.java cpsc2150/banking/models/AbsCustomer.java cpsc2150/banking/models/AbsMortgage.java cpsc2150/banking/models/Customer.java cpsc2150/banking/models/ICustomer.java cpsc2150/banking/models/IMortgage.java cpsc2150/banking/models/Mortgage.java cpsc2150/banking/views/IMortgageView.java cpsc2150/banking/views/MortgageView.java cpsc2150/banking/MortgageApp.java

run: cpsc2150/banking/controllers/MortgageController.class cpsc2150/banking/models/AbsCustomer.class cpsc2150/banking/models/AbsMortgage.class cpsc2150/banking/models/Customer.class cpsc2150/banking/models/Mortgage.class cpsc2150/banking/views/MortgageView.class cpsc2150/banking/MortgageApp.class
	java cpsc2150.banking.MortgageApp

clean:
	rm -f cpsc2150/banking/*.class
	rm -f cpsc2150/banking/*/*.class