default: cpsc2150/sets/ISet.java cpsc2150/sets/DoubleSetApp.java cpsc2150/sets/ArraySet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java
	javac -Xlint cpsc2150/sets/ISet.java cpsc2150/sets/DoubleSetApp.java cpsc2150/sets/ArraySet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java

run: cpsc2150/sets/ISet.java cpsc2150/sets/DoubleSetApp.java cpsc2150/sets/ArraySet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java
	java cpsc2150.sets.DoubleSetApp

clean:
	rm -f cpsc2150/sets/*.class
